### PR TITLE
rev 5b

### PR DESCRIPTION
**Pull request by nbovee**
Thought others might find this layout useful, though not sure how you would want to handle versioning. Created PCB to support moving L3 & R3 to below the lower row inspired from Daigo's layout. Solder jumpers are used to select these new keys. Cases to match also created.

### CODE REVIEW

**Comment by over-fitted** [comment]
LGTM, just sent a set of PCBs for print, might update when I finish

Thanks!

**Comment by JarTheHead** [comment]
I feel like this could work really well as a Rev 4 fork too since the processor is on board. Not sure how hard it would be to adjust that board tho.

**Comment by nbovee** [comment]
> I feel like this could work really well as a Rev 4 fork too since the processor is on board. Not sure how hard it would be to adjust that board tho.

The IO doesn't change so can't be too hard. We'll see how jfedor wants to handle revs/merges first, then can possibly circle back.

**Comment by jfedor2** [comment]
I'd like to stick with things I made or at least tested myself on this repo so just keep a fork on your account. Ideally make it clear what's changed in the README and include pictures. I'm thinking of keeping a list of remixes on a wiki page, but haven't got around to it yet.

**Comment by nbovee** [comment]
Ok, that's fine if it's not open for PR. I'll leave this for people who want to use it but otherwise will redirect design efforts.

For completeness, text details are already in, updated images for clarity.

**Comment by nbovee** [comment]
Oops. For those who wanted the design this PR is [here](https://github.com/nbovee/flatbox/tree/5B-PR-stub), but I needed my master branch back since additional pushes would update this.

**Pull request closed without merging**
